services:
# velocity
  velocity: 
    stdin_open: true
    tty: true
    container_name: mc-velocity
    image: itzg/mc-proxy
    restart: unless-stopped
    networks:
      - velocity
    volumes: 
      - ./mc-velocity:/server
    ports:
      - "25565:25577"
    environment:
      TYPE: VELOCITY 
      MEMORY: 512M
# main
  main:
    container_name: mc-main
    image: itzg/minecraft-server
    restart: unless-stopped
    networks:
      - velocity
    volumes:
      - ./mc-main:/data
    environment:
      EULA: 'TRUE'
      TYPE: CUSTOM
      CUSTOM_SERVER: https://github.com/Winds-Studio/Leaf/releases/download/ver-1.21.1/leaf-1.21.1.jar
      VERSION: '1.21.1'
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
networks:
  velocity:
    name: velocity-network
    